apiVersion: apps/v1
kind: Deployment
metadata:
  name: a2a-registry-private-staging
  namespace: private-staging
  labels:
    app: a2a-registry-private-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a2a-registry-private-staging
  template:
    metadata:
      labels:
        app: a2a-registry-private-staging
    spec:
      serviceAccountName: tailscale
      containers:
      - name: a2a-registry
        image: gcr.io/a2a-registry-dev/a2a-registry:latest
        ports:
        - containerPort: 8000
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8000"
        - name: STORAGE_TYPE
          value: "file"
        - name: STORAGE_DATA_DIR
          value: "/data"
        - name: ENVIRONMENT
          value: "private-staging"
        volumeMounts:
        - name: registry-data
          mountPath: /data
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      - name: tailscale
        image: "tailscale/tailscale:latest"
        env:
        - name: TS_KUBE_SECRET
          value: "tailscale-auth"
        - name: TS_USERSPACE
          value: "true"
        - name: TS_HOSTNAME
          value: "a2a-registry-private-staging"
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        volumeMounts:
        - name: tailscale-state
          mountPath: /var/lib/tailscale
      volumes:
      - name: registry-data
        persistentVolumeClaim:
          claimName: registry-data-private-staging-pvc
      - name: tailscale-state
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: a2a-registry-private-staging-service
  namespace: private-staging
  labels:
    app: a2a-registry-private-staging
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: a2a-registry-private-staging
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data-private-staging-pvc
  namespace: private-staging
  labels:
    app: a2a-registry-private-staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi