name: Terraform Infrastructure

on:
  push:
    branches: [ main ]
    paths: [ 'deploy/terraform/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'deploy/terraform/**' ]
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform'
        required: true
        default: 'plan'
        type: choice
        options:
        - plan
        - apply
        - destroy
        - import
      environment:
        description: 'Environment to deploy to'
        required: false
        default: 'production'
        type: choice
        options:
        - production
        - staging
        - private-staging
      auto_approve:
        description: 'Auto-approve apply/destroy (use with caution)'
        required: false
        default: false
        type: boolean
      import_resource:
        description: 'Resource to import (e.g., google_service_account.tailscale)'
        required: false
        type: string
      import_id:
        description: 'Resource ID to import'
        required: false
        type: string

env:
  TF_VERSION: "1.5.7"
  TF_WORKING_DIR: "deploy/terraform"
  TF_VAR_environment: ${{ github.event.inputs.environment || 'production' }}

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'production' }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        create_credentials_file: true
        export_environment_variables: true
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker

    - name: Terraform Init
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform init

    - name: Terraform Format Check
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform fmt -check

    - name: Terraform Validate
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform validate

    - name: Import Resources
      if: |
        github.event_name == 'workflow_dispatch' && 
        github.event.inputs.action == 'import'
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: |
        # Remove all resources from state
        terraform state rm google_service_account.tailscale || true
        terraform state rm google_compute_subnetwork.private_staging || true
        terraform state rm google_compute_firewall.tailscale || true
        terraform state rm google_project_iam_member.tailscale_node || true
        terraform state rm google_container_node_pool.private_staging_nodes || true
        terraform state rm google_project_service.cloudresourcemanager || true
        terraform state rm 'google_project_service.required_apis["compute.googleapis.com"]' || true
        terraform state rm 'google_project_service.required_apis["container.googleapis.com"]' || true
        terraform state rm 'google_project_service.required_apis["iam.googleapis.com"]' || true
        terraform state rm 'google_project_service.required_apis["serviceusage.googleapis.com"]' || true
        
        # Import resources
        terraform import google_service_account.tailscale projects/${{ secrets.GCP_PROJECT_ID }}/serviceAccounts/tailscale-sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com || true
        terraform import google_compute_subnetwork.private_staging projects/${{ secrets.GCP_PROJECT_ID }}/regions/us-central1/subnetworks/private-staging-subnet || true
        terraform import google_compute_firewall.tailscale projects/${{ secrets.GCP_PROJECT_ID }}/global/firewalls/allow-tailscale || true
        
        # Import generic resource if specified
        if [ ! -z "${{ github.event.inputs.import_resource }}" ] && [ ! -z "${{ github.event.inputs.import_id }}" ]; then
          terraform state rm ${{ github.event.inputs.import_resource }} || true
          terraform import ${{ github.event.inputs.import_resource }} ${{ github.event.inputs.import_id }}
        fi

    - name: Terraform Plan
      id: plan
      working-directory: ${{ env.TF_WORKING_DIR }}
      if: github.event.inputs.action != 'destroy' && github.event.inputs.action != 'import'
      run: |
        terraform plan -detailed-exitcode -out=tfplan
        echo "plan_exit_code=$?" >> $GITHUB_OUTPUT
      continue-on-error: true

    - name: Terraform Plan Status
      if: steps.plan.outputs.plan_exit_code == 1
      run: exit 1

    - name: Terraform Plan Status
      if: steps.plan.outputs.plan_exit_code == 2
      run: echo "Changes detected"

    - name: Comment PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const output = `#### Terraform Plan 📋
          \`\`\`\n
          ${process.env.PLAN || 'No changes. Infrastructure is up-to-date.'}
          \`\`\`
          
          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })

    - name: Terraform Apply
      if: |
        github.event_name == 'workflow_dispatch' && 
        github.event.inputs.action == 'apply' &&
        (github.event.inputs.auto_approve == 'true' || github.actor == 'allenday')
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: |
        # Remove all resources from state
        terraform state rm google_service_account.tailscale || true
        terraform state rm google_compute_subnetwork.private_staging || true
        terraform state rm google_compute_firewall.tailscale || true
        terraform state rm google_project_iam_member.tailscale_node || true
        terraform state rm google_container_node_pool.private_staging_nodes || true
        terraform state rm google_project_service.cloudresourcemanager || true
        terraform state rm 'google_project_service.required_apis["compute.googleapis.com"]' || true
        terraform state rm 'google_project_service.required_apis["container.googleapis.com"]' || true
        terraform state rm 'google_project_service.required_apis["iam.googleapis.com"]' || true
        terraform state rm 'google_project_service.required_apis["serviceusage.googleapis.com"]' || true
        
        # Import resources
        terraform import google_service_account.tailscale projects/${{ secrets.GCP_PROJECT_ID }}/serviceAccounts/tailscale-sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com || true
        terraform import google_compute_subnetwork.private_staging projects/${{ secrets.GCP_PROJECT_ID }}/regions/us-central1/subnetworks/private-staging-subnet || true
        terraform import google_compute_firewall.tailscale projects/${{ secrets.GCP_PROJECT_ID }}/global/firewalls/allow-tailscale || true
        
        # Always create a new plan before applying
        terraform plan -out=tfplan
        terraform apply -auto-approve tfplan

    - name: Terraform Destroy
      if: |
        github.event_name == 'workflow_dispatch' && 
        github.event.inputs.action == 'destroy' &&
        github.event.inputs.auto_approve == 'true' &&
        github.actor == 'allenday'
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: |
        terraform destroy -auto-approve

    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v4
      if: steps.plan.outputs.plan_exit_code == 2
      with:
        name: terraform-plan
        path: ${{ env.TF_WORKING_DIR }}/tfplan